name: Check Copywrite Headers

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  copywrite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: hashicorp/setup-copywrite@32638da2d4e81d56a0764aa1547882fc4d209636 # v1.1.3
        name: Setup Copywrite
        with:
          version: v0.22.0
          archive-checksum: 072863a5c35e61587dc24f7a8201a9ab9d1158989235334abc4fe2fb412095ed
      - name: Check Header Compliance
        run: copywrite headers --plan

permissions:
  contents: read
